zuul:
  # Disable accessing services using service name (i.e. greeting-service).
  # They should be only accessed through the path defined below.
  ignored-services: '*'

  # Map paths to services
  routes:
    auth-service:
      path: /api/auth/**
      service-id: auth-service
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie
    greeting-service:
      path: /api/greetings/**
      service-id: greeting-service
      strip-prefix: false
    author-service:
      path: /api/authors/**
      service-id: author-service
      strip-prefix: false
    book-service:
      path: /api/books/**
      service-id: book-service
      strip-prefix: false
